name: readuslive
description: A modern mobile app for ReadUsLive with GetX state management.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  get: ^4.6.5
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.7
  cached_network_image: ^3.3.0
  smooth_page_indicator: ^1.1.0
  fl_chart: ^0.64.0
  intl: ^0.18.1
  shared_preferences: ^2.2.1
  flutter_rating_bar: ^4.0.1
  table_calendar: ^3.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.3

flutter:
  uses-material-design: true
  assets:
    - images/